#!/bin/bash
# -----------------------------------------------------------
# TITLE: LazyWGET - Lazy, recursive HTML file download
# AUTHORS: Cristian Budala, Ruslan Gaitur
# DATE: 2025-12
# -----------------------------------------------------------
# DESCRIPTION:
# This script performs recursive, breadth-first download of HTML
# files from a given URL, advancing one level of depth further for each run
#
# USAGE:
# ./lwget <URL>
# ./lwget --reset (to clear the cache)
	#
# DEPENDENCIES:
# - wget: Used for downloading the files
# - grep, awk, cut: Used for link extraction and promise processing & management
# -----------------------------------------------------------

### CONFIG. FILES ###
WORK_DIR="./lwget_cache"
DOWNLOADS_DIR="$WORK_DIR/downloads"
METADATA_DIR="$WORK_DIR/.metadata" # hidden file
PROMISES_FILE="$METADATA_DIR/promises.txt"
LEVEL_FILE="$METADATA_DIR/current_level.txt"

mkdir -p "$DOWNLOADS_DIR"
mkdir -p "$METADATA_DIR"
# -----------------------------------------------------------

usage(){
	cat << EOF

USAGE:
   ./lwget <URL>

OPTIONS:
   <URL>        The base URL where download starts. Only HTTP and HTTPS are accepted. (REQUIRED)
   -h, --help   Print help instructions.
   -r      		Deletes working directory (lwget_cache) and resets progress.

DEPENDENCIES:
   wget, grep, awk, cut

EOF
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	usage
	exit 0
fi

download_file(){
	< $DOWNLOADS_DIR
	local url="$1"
	local output_file="$2"
	wget -q -O "$output_file" "$url" # no output (quiet), writes documents to file: -O
}

extract_links(){
    local filename="$1"
	# from the html file, grep prints to stdout only the matching part (-o) of links (not the entire html declaration of the object), splits it by " and prints the second argument
    grep -o 'href="http[^"]*"' "$filename" | awk -F'"' '{print $2}'
}

get_current_level(){
	cat < $LEVEL_FILE
}

save_promises(){
	local level=$(get_current_level)
	local urls="$2"
	while read -r url; do
		echo "$level|$url" >> "$PROMISES_FILE"
	done <<< "$urls"
}

reset_meta() {
	if [ -f "$LEVEL_FILE" ]; then
		rm "$LEVEL_FILE"
		echo "Cleared level meta before initialization"
	fi

	if [ -f "$PROMISES_FILE" ]; then
		rm "$PROMISES_FILE"
		echo -e "Cleared promises meta before initialization \n"
	fi

	exit 0
}

if [ "$1" == "-r" ]; then
	reset_meta
fi

init(){
	if [ ! -f "$LEVEL_FILE" ]; then
		echo "0" > "$LEVEL_FILE"
		echo "Initialized level 0"
	fi

	if [ ! -f "$PROMISES_FILE" ]; then
		touch "$PROMISES_FILE"
		echo -e "Initialized promises at level 0 \n"
	fi
}

get_promises_for_level(){
	local level="$1"
	grep "^$level|" "$PROMISES_FILE" | cut -d "|" -f 2
}

parse_promises() {
	for item in $(get_promises_for_level $(($(get_current_level) - 1)))
	{
		echo $item
		url=$item
		if [[ "$item" =~ \.(pdf|jpg|png|zip|css|js|svg)$ ]]; then 
			resource_name=$(basename "$url")
			local assets_dir="$DOWNLOADS_DIR/assets"
			mkdir -p "$assets_dir"
			wget -q -nc -x -P "$assets_dir" "$url"
		else 
			local output_file="$DOWNLOADS_DIR/downloaded.html"
			download_file "$url" "$output_file"
			local urls=$(extract_links "$output_file")
			save_promises "$(get_current_level)" "$urls"
		fi
	}
	
	echo -e "\nFinished parsing level $(get_current_level)... \n"

	# Increment level after parsing
	echo $(($(get_current_level)+1)) > $LEVEL_FILE
}

main(){
	local url="$1"
	local current_level=$(get_current_level)
	echo "Current level: $current_level"

	if [ "$current_level" -eq 0  ]; then
		if [ $# -eq 0 ]; then
			echo "You must enter an URL!"
			echo "Usage: $0 <URL>"
			exit 1
		fi

		if [ $# -gt 1 ]; then
			echo "You must enter a single <URL>!"
			echo "Usage: $0 <URL>"
			exit 1
		fi

		echo "--- Level 0: Downloading root file ---"
		local output_file="$DOWNLOADS_DIR/downloaded.html"

		download_file "$url" "$output_file"
		echo ""
		echo "Download complete!"
		echo ""
	
		local urls=$(extract_links "$output_file")
		echo "Found links:"
		echo "$urls"
		echo ""

		save_promises "1" "$urls"
		echo "Promises saved to $PROMISES_FILE"
		echo "1" > "$LEVEL_FILE"
	else
		echo "--- Level $current_level: Processing promises ---"
		parse_promises
	fi
}

init "$@" 
main "$@"

